---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: public.ecr.aws/r5m2h0c9/high-cardinality-generator:v1
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
